[build]
  command = "npm run build"  # Remove this line if you're not using a build system
  publish = "/"             # Your files are in the root directory
  functions = "functions"   # Points to your functions directory

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
